version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=MySecureP@ssw0rd123!
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build:
      context: .  # Contexte de construction, indique le répertoire contenant le Dockerfile
      dockerfile: dockerfile  # Nom du Dockerfile (veuillez vérifier la casse)
    container_name: spring-container
    depends_on:
      - mysql
    ports:
      - "8082:8082"  # Mapping pour le port 8082
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/devops?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=phpmyadmin
      - SPRING_DATASOURCE_PASSWORD=MySecureP@ssw0rd123!
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .:/app  # Montre le répertoire actuel dans /app du conteneur

networks:
  my-network:

volumes:
  mysql-data:
