version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tools-network

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - tools-network
    depends_on:
      - prometheus

  sonar:
    image: sonarqube:8.9.7-community
    container_name: keen_spence
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - tools-network
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - tools-network
    volumes:
      - nexus_data:/nexus-data

networks:
  tools-network:

volumes:
  sonarqube_conf:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local
  nexus_data:
    driver: local

